-- schema v1 snapshot (code record only, not executed on app start)
-- 적용 순서: cinemas → rooms → seats → genres → movies → movie_genres
--            → screenings → users → bookings → booked_seats

CREATE TABLE IF NOT EXISTS cinemas (
    cinema_id   INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cinema_name VARCHAR(100) NOT NULL UNIQUE,
    address     VARCHAR(255) NOT NULL,
    cs_number   VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS rooms (
    room_id     INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cinema_id   INTEGER NOT NULL REFERENCES cinemas (cinema_id) ON DELETE CASCADE,
    room_name   VARCHAR(50) NOT NULL,
    floor       INTEGER NOT NULL,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS seats (
    seat_id     INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    room_id     INTEGER NOT NULL,
    row_name    CHAR(1) NOT NULL,
    col_num     INTEGER NOT NULL,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_seats_room
        FOREIGN KEY (room_id)
        REFERENCES rooms (room_id)
        ON DELETE RESTRICT,
    CONSTRAINT uk_seats_room_row_col
        UNIQUE (room_id, row_name, col_num)
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id    INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    genre_name  VARCHAR(50) NOT NULL,
    CONSTRAINT uk_genres_name
        UNIQUE (genre_name)
);

CREATE TABLE IF NOT EXISTS movies (
    movie_id     INTEGER PRIMARY KEY,
    title        VARCHAR(200),
    age_limit    INTEGER,
    running_time INTEGER,
    release_date TIMESTAMP,
    content      VARCHAR(2000),
    director     VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS movie_genres (
    movie_genre_id  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    movie_id        INTEGER NOT NULL,
    genre_id        INTEGER NOT NULL,
    CONSTRAINT fk_movie_genres_movie
        FOREIGN KEY (movie_id)
        REFERENCES movies (movie_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_movie_genres_genre
        FOREIGN KEY (genre_id)
        REFERENCES genres (genre_id)
        ON DELETE RESTRICT,
    CONSTRAINT uk_movie_genres_movie_genre
        UNIQUE (movie_id, genre_id)
);

CREATE TABLE IF NOT EXISTS screenings (
    screening_id   INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cinema_id      INTEGER NOT NULL,
    room_id        INTEGER NOT NULL,
    movie_id       INTEGER NOT NULL,
    screening_date DATE NOT NULL,
    start_time     TIME NOT NULL,
    end_time       TIME NOT NULL,
    CONSTRAINT fk_screening_cinema FOREIGN KEY (cinema_id) REFERENCES cinemas (cinema_id),
    CONSTRAINT fk_screening_room FOREIGN KEY (room_id) REFERENCES rooms (room_id),
    CONSTRAINT fk_screening_movie FOREIGN KEY (movie_id) REFERENCES movies (movie_id)
);

CREATE TABLE IF NOT EXISTS users (
    user_id     INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    login_id    VARCHAR NOT NULL UNIQUE,
    user_pw     VARCHAR NOT NULL,
    name        VARCHAR NOT NULL,
    age         INTEGER,
    phone_number VARCHAR NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted  BOOLEAN DEFAULT FALSE NOT NULL,
    deleted_at  TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS bookings (
    booking_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER NOT NULL,
    movie_id        VARCHAR NOT NULL,
    screening_id    INTEGER NOT NULL,
    booking_status  booking_status_type NOT NULL DEFAULT 'DONE',
    booking_date    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    canceled_date   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bookings_users
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS booked_seats (
    booked_seat_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    booking_id     INTEGER NOT NULL,
    seat_id        INTEGER NOT NULL,
    screening_id   INTEGER NOT NULL,
    CONSTRAINT fk_booked_seats_booking
        FOREIGN KEY (booking_id)
        REFERENCES bookings (booking_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_booked_seats_seat
        FOREIGN KEY (seat_id)
        REFERENCES seats (seat_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_booked_seats_screening
        FOREIGN KEY (screening_id)
        REFERENCES screenings (screening_id)
        ON DELETE RESTRICT,
    CONSTRAINT uk_booked_seats_screening_seat
        UNIQUE (screening_id, seat_id)
);
